# RANDOM VECTORS - LINEAR COMBINATIONS

## TUTORIAL

For vectors $\vec X = (X_0, X_1, \cdots)$ and $\vec Y = (Y_0, Y_1, \ldots)$, a linear combination $\vec Z = a\vec X + b\vec Y$ for scalars $a, b$ has components $Z_i = aX_i + bY_i$. Recall that each component $X_i, Y_i$ are random variables, and so therefore is $Z_i$. Note importantly that $Z_i$ is a sum of *independent* random variables $X_i, Y_i$. When forming linear conbinations in this way, we necessarily assume $\vec X$ and $\vec Y$ are independent.

**Remark.** *More generally, $a$ and $b$ can be random variables. In this case, for all $i$ they are independent of $X_i$ and $Y_i$ respectively*

Much like the `RandVar` class, the `RandVec` class is appropriate when forming linear combinations of random vectors. 

### LIBRARY IMPORTS

Below are all the library imports relevantv for this tutorial.

In [1]:
from pystochastica.discrete.vectors import RandVec as rvec
from pystochastica.discrete.core import JointDistribution as jd
from pystochastica.discrete.utils import generate_jdist_random

from pystochastica.discrete.variables import RandVar as rvar
from pystochastica.discrete.core import JointDistribution as jd
from pystochastica.discrete.utils import rvdict_to_init
from pystochastica.discrete.utils import generate_jdist

from fractions import Fraction

### SCALAR COMBINATION

We initialise two vectors through the utility function `generate_jdist_random` and form a sample linear combination with scalars `a` and `b` as follows.

In [2]:
X_vec = rvec(pspace=jd(pspace=generate_jdist_random(dimension=2)).pspace)
Y_vec = rvec(pspace=jd(pspace=generate_jdist_random(dimension=2)).pspace)

a = 12.5
b = -3

Z_vec = a*X_vec + b*Y_vec
Z_vec.E, Z_vec.V

(array([-294.61605889,  504.62986124]),
 array([[3.58826015e+04, 5.82076609e-11],
        [5.82076609e-11, 1.73605805e+04]]))

### FUNCTIONAL COMBINATION

In addition to scalars `a` and `b` above, random vectors can also be multiplied by random variables. If $\vec Y = (Y_0, Y_1, \ldots)$ is a random vector and $X$ is a random variable, then $\vec Z = X\vec Y$ is the random variable with components $Z_i = XY_i$. 

In `pystochastica` this is represented through the ability to multiply `RandVec` objects by `RandVar`, returning another `RandVec` object. We demonstrate a functional combination of `X_vec` and `Y_vec` with random variables `A` and `B` below.

**Note.** *The probabilities in the probability spaces for `X_vec` and `Y_vec` are `fraction.Fraction` objects. It is important that the probabiltiies initialising `A` and `B` below are also `fraction.Fraction` objects. Otherwise a `TypeError` error will be raised.*


In [3]:
A_init = {
    'name': 'X', 
    'pspace': {
        '-1': Fraction(37, 100),
        '0': Fraction(20, 100),
        '1': Fraction(43, 100)
    }}
A_var = rvar(**rvdict_to_init(A_init))

B_init = {
    'name': 'Y', 
    'pspace': {
        '-1': Fraction(40, 100),
        '1': Fraction(60, 100)
    }}
B_var = rvar(**rvdict_to_init(B_init))

Z2_vec = A_var*X_vec + B_var*Y_vec
Z2_vec.E

array([0.649568  , 2.03817484])

### VECTOR DOT, SUM AND NORM

Through the dot product of vectors, we can form its norm-square $\|\vec X\|^2$ and its component sum $|\vec X| = X\cdot \mathbf 1$, for $\mathbf 1$ an appropriate sized vector of ones. 

For `RandVec` objects the `@` symbol, defined through `__matmul__`, returns the dot product. This means we can readily form random variables through the norm and vector sum on random vectors (c.f., `ndarray` objects in the Python `numpy` library).

For `Z_vec` above, its norm and vector sum are as below, along with their expectation ad variance:

In [4]:
Z_vec_norm = Z_vec @ Z_vec
Z_vec_sum = Z_vec.sum()

print(f"{Z_vec_norm.E = }\t{Z_vec_norm.V = }\n{Z_vec_sum.E = }\t{Z_vec_sum.V = }")

Z_vec_norm.E = 341449.9190142199	Z_vec_norm.V = 16659860279.95668
Z_vec_sum.E = 210.0138023459032	Z_vec_sum.V = 53243.182021923974


More generally, the dot product of any two random vectors of the same dimension can be formed to return a random variable. 

For `Z_vec` and `Z2_vec` from above, the expectation and variance of their dot product is as follows.

In [5]:
Z_Z2 = Z_vec @ Z2_vec

print(f"{Z_Z2.E = }\t{Z_Z2.V = }")

Z_Z2.E = 837.1507188544149	Z_Z2.V = 653646602.7543957
